platform :ios, '11.0'
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end

target 'IoniconsKit_Example' do
  pod 'IoniconsKit', :path => '../'
end
